name: Pandoc

on:
  push:
    branches:
      - master
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Say hello
        run: echo Hello, world!
      - uses: docker://pandoc/latex:2.9
        with:
          args: --standalone -o test.pdf  test.md
      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: pdf
          path: test.pdf
